### PR TITLE
run on m1 mac runners

### PR DESCRIPTION
**Pull request by sagikazarmark**

### CODE REVIEW

**Comment by kgantchev** [comment]
@sagikazarmark this looks fantastic! So happy that you're enjoying the FlyCI M1 runners!

image

**Comment by kgantchev** [comment]
BTW, how did you hear about FlyCI?

**Comment by sagikazarmark** [comment]
@kgantchev Thanks!

It's not perfect though, I had to workaround some disk space issues and one of the builds are still breaking, but it's still better than before.

I saw it in your comment on the GitHub forum: https://github.com/orgs/community/discussions/69211#discussioncomment-7941899

It's gonna be interesting to see how it matches up against GHA's runners in the long run. Honestly, GHA has been a major letdown recently (ie. the past 6 months or so).

**Comment by kgantchev** [comment]
@sagikazarmark thanks for the invaluable feedback. I'll pass it on to the team.

**Pull request merged**
